networking:
  baseIP: "0.0.0.0"
  raspIP: "192.168.1.100"
  retryDelaySec: 2

notifier:
  assetsPath: "./assets/audio"

autopilot:
  port: 2000
  maxBackwardPWM: 1100
  maxForwardPWM: 1900
  neutralPWM: 1500
  gainLevels: [25, 40, 50, 75, 90]
  timeoutSec: 2

manfaloty:
  port: 2005

piTelemetry:
  port: 2010

piAdmin:
  port: 2015

controller:
  joystickDeadZoneFactor: 2
  joystickRoundOff: 1
  joystickMultiplier: 100
  mappings:
    - name: "zizo-style"
      mappings:
        ARM: "R"
        DISARM: "L"
        GAIN_UP: "3"
        GAIN_DOWN: "1"
        ROLL_RIGHT: "2"
        ROLL_LEFT: "4"
        STABILIZATION_MODE: "C"
        MANUAL_MODE: "D"
        GRIPPER_ROLL_LEFT: "L4"
        GRIPPER_ROLL_RIGHT: "R4"
        GRIPPER_PITCH_UP: "R2"
        GRIPPER_PITCH_DOWN: "L2"
        GRIPPER_JAW_OPEN: "R1"
        GRIPPER_JAW_CLOSE: "L1"
        FORWARD:
          joystick: "L"
          axis: "Y"
        LATERAL:
          joystick: "L"
          axis: "X"
        THROTTLE:
          joystick: "R"
          axis: "Y"
        YAW:
          joystick: "R"
          axis: "X"

  configs:
    - displayName: 8BitDo 2C Ultimate Bluetooth
      pygameName: 8BitDo Ultimate 2C Wireless
      buttons: 16
      axes: 6
      hats: 1
      mappings:
        '1':
          type: hat
          mapping:
          - 0
          - -1
        '2':
          type: hat
          mapping:
          - 1
          - 0
        '3':
          type: hat
          mapping:
          - 0
          - 1
        '4':
          type: hat
          mapping:
          - -1
          - 0
        A:
          type: button
          mapping:
          - 0
        B:
          type: button
          mapping:
          - 1
        C:
          type: button
          mapping:
          - 4
        D:
          type: button
          mapping:
          - 3
        L:
          type: button
          mapping:
          - 10
        M:
          type: button
          mapping:
          - 12
        R:
          type: button
          mapping:
          - 11
        LJ:
          type: axis
          axis:
          - 0
          - 1
        L1:
          type: button
          mapping:
          - 6
        L2:
          type: button
          mapping:
          - 8
        L3:
          type: button
          mapping:
          - 13
        L4:
          type: button
          mapping:
          - 2
        RJ:
          type: axis
          axis:
          - 2
          - 3
        R1:
          type: button
          mapping:
          - 7
        R2:
          type: button
          mapping:
          - 9
        R3:
          type: button
          mapping:
          - 14
        R4:
          type: button
          mapping:
          - 5
    - displayName: 8BitDo 2C Ultimate Wired
      pygameName: 8BitDo Ultimate 2C Wireless Controller
      buttons: 11
      axes: 6
      hats: 1
      mappings:
        '1':
          type: hat
          mapping:
          - 0
          - -1
        '2':
          type: hat
          mapping:
          - 1
          - 0
        '3':
          type: hat
          mapping:
          - 0
          - 1
        '4':
          type: hat
          mapping:
          - -1
          - 0
        A:
          type: button
          mapping:
          - 0
        B:
          type: button
          mapping:
          - 1
        C:
          type: button
          mapping:
          - 3
        D:
          type: button
          mapping:
          - 2
        L:
          type: button
          mapping:
          - 6
        M:
          type: button
          mapping:
          - 8
        R:
          type: button
          mapping:
          - 7
        LJ:
          type: axis
          axis:
          - 0
          - 1
        L1:
          type: button
          mapping:
          - 4
        L2:
          type: trigger
          axis:
          - 2
        L3:
          type: button
          mapping:
          - 9
        RJ:
          type: axis
          axis:
          - 3
          - 4
        R1:
          type: button
          mapping:
          - 5
        R2:
          type: trigger
          axis:
          - 5
        R3:
          type: button
          mapping:
          - 10
    - displayName: Default
      pygameName: ''
      buttons: 16
      axes: 6
      hats: 0
      mappings:
        '1':
          type: button
          mapping:
          - 12
        '2':
          type: button
          mapping:
          - 14
        '3':
          type: button
          mapping:
          - 11
        '4':
          type: button
          mapping:
          - 13
        A:
          type: button
          mapping:
          - 0
        B:
          type: button
          mapping:
          - 1
        C:
          type: button
          mapping:
          - 3
        D:
          type: button
          mapping:
          - 2
        L:
          type: button
          mapping:
          - 4
        M:
          type: button
          mapping:
          - 5
        R:
          type: button
          mapping:
          - 6
        LJ:
          type: axis
          axis:
          - 0
          - 1
        L1:
          type: button
          mapping:
          - 9
        L2:
          type: trigger
          axis:
          - 4
        L3:
          type: button
          mapping:
          - 7
        L4:
          type: button
          mapping:
          - 6
          - 9
        RJ:
          type: axis
          axis:
          - 2
          - 3
        R1:
          type: button
          mapping:
          - 10
        R2:
          type: trigger
          axis:
          - 5
        R3:
          type: button
          mapping:
          - 8
        R4:
          type: button
          mapping:
          - 6
          - 10
    - displayName: DualShock 4 Alternate
      pygameName: PS4 Controller
      buttons: 16
      axes: 6
      hats: 0
      mappings:
        '1':
          type: button
          mapping:
          - 12
        '2':
          type: button
          mapping:
          - 14
        '3':
          type: button
          mapping:
          - 11
        '4':
          type: button
          mapping:
          - 13
        A:
          type: button
          mapping:
          - 0
        B:
          type: button
          mapping:
          - 1
        C:
          type: button
          mapping:
          - 3
        D:
          type: button
          mapping:
          - 2
        L:
          type: button
          mapping:
          - 4
        M:
          type: button
          mapping:
          - 5
        R:
          type: button
          mapping:
          - 6
        LJ:
          type: axis
          axis:
          - 0
          - 1
        L1:
          type: button
          mapping:
          - 9
        L2:
          type: trigger
          axis:
          - 4
        L3:
          type: button
          mapping:
          - 7
        RJ:
          type: axis
          axis:
          - 2
          - 3
        R1:
          type: button
          mapping:
          - 10
        R2:
          type: trigger
          axis:
          - 5
        R3:
          type: button
          mapping:
          - 8



